# Gazelle WiFi TUI - floating window like Impala
#windowrulev2 = float, class:^(Gazelle)$
#windowrule = float on, center on, size 800 600, match:initial_class Gazelle

# discord
windowrule = workspace 3, match:class discord
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class discord

# Spotify
windowrule = workspace 3, match:class spotify

#Zen
windowrule = no_blur on, match:class zen
windowrule = opacity 1.0 override 1.0 override 1.0 override, match:class zen

#Steam
# Force all Steam windows to tile and stay tiled
windowrule = tile on, match:class steam
windowrule = suppress_event float maximize activate, match:class steam

windowrule = opacity 1.0 override, match:class ^steam_app_\d+$
