# Set default workspaces
# Use aliases defined in monitors.conf
# Center monitor (Predator) for primary work and apps
workspace = r[1-8], monitor:$predator

# Side monitors for specific apps
workspace = 9, monitor:$benq_left
workspace = 10, monitor:$benq_right

# Workspace for games
workspace = name:game, monitor:$predator
