# Set default workspaces
# Use aliases defined in monitors.conf
# Center monitor (Predator) for primary work and apps
workspace = 1, monitor:$predator, persistent:true, default:true
workspace = 2, monitor:$predator, persistent:true
workspace = 3, monitor:$predator, persistent:true
workspace = 4, monitor:$predator, persistent:true
workspace = 5, monitor:$predator, persistent:true
workspace = 6, monitor:$predator, persistent:true
workspace = 7, monitor:$predator, persistent:true
workspace = 8, monitor:$predator, persistent:true

# Side monitors for specific apps
workspace = 9, monitor:$benq_left, persistent:true, default:true
workspace = 10, monitor:$benq_right, persistent:true, default:true
