# Set default workspaces
# Use aliases defined in monitors.conf
workspace = 1, monitor:$predator
workspace = 2, monitor:$benq_right
workspace = 3, monitor:$benq_left

# Catch-all: Ensure any other new workspaces (4-100) are spawned on the center monitor
workspace = r[4-100], monitor:$predator

# Workspace for games
workspace = name:game, monitor:$predator
